Django-Python/sampleproject/index/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("timeDisplay", views.timeDisplay, name="timeDisplay"),
    path("akira", views.swetch, name="swetch"),
    path("<str:name>", views.introduction, name="introduction")
]

Django-Python/sampleproject/newyear/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.index, name="index")
]

Django-Python/sampleproject/sampleproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include("index.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls"))
]

Django-Python/sampleproject/tasks/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "tasks"

urlpatterns = [
    path("", views.taskList, name="home"),
    path("add", views.addTask, name="add"),
    path("clear", views.clearSesh, name="clear"),
    path("edit", views.editTask, name="edit")
]

Django-Python/sampleproject/index/models.py
from django.db import models

# Create your models here.

Django-Python/sampleproject/newyear/models.py
from django.db import models

# Create your models here.

Django-Python/sampleproject/tasks/models.py
from django.db import models

# Create your models here.

Django-Python/sampleproject/tasks/forms.py
from django import forms

class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")

class EditTaskForm(forms.Form):
    taskNum = forms.CharField(label="Task Count")
    updateTask = forms.CharField(label="Update Task")

Django-Python/sampleproject/index/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django import forms
from datetime import datetime
from django.urls import reverse

# Create your views here.

def index(request):
    return render(request, "index/index.html")

def timeDisplay(request):
    time = datetime.now().time()
    return HttpResponse(f"Current Time: {time}")

def introduction(request, name):

    if name == " " or name == None:
        name = "twitch.tv/maikonshu"

    return render(request, "index/index.html", {
        "name" : name.capitalize()
    })

listMen = ["Carlos", "Ainz", "Asuka"]

def swetch(request):
    return render(request, "index/synchro.html", {
        "men" : listMen
    })

Django-Python/sampleproject/newyear/views.py
import datetime
from django.shortcuts import render

# Create your views here.

def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/newyear.html", {
        "currDate": now.month == 1 and now.day == 1
    })

Django-Python/sampleproject/tasks/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django import forms
from .forms import NewTaskForm
from .forms import EditTaskForm

# Create your views here.

tasks = ["foo", "bar", "fun"]

def taskList(request):
    
    if 'tasks' not in request.session:
        request.session['tasks'] = []

    return render(request, "tasks.html", {
        "tasks" : request.session["tasks"],
        "formEdit" : EditTaskForm()
    })

def addTask(request):

    if request.method == "POST":
        task = request.POST.get("task")

        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]

            return HttpResponseRedirect(reverse("tasks:home"))
    
    return render(request, "add.html", {
        "form" : NewTaskForm()
    })

# def editTask(request):
#     if request.method == "POST":
#         task = request.POST.get("newTask")
#         taskNum = request.POST.get("listNum")
#         taskList = request.session["tasks"]
#         print(task)
#         print(taskNum)

#         oldTask = request.session["tasks"][int(taskNum) - 1]
#         print(oldTask)

#         request.session["tasks"][int(taskNum) - 1] = task

#         form = EditTaskForm(request.POST)
#         if form.is_valid():
#             task = form.cleaned_data("newTask")
#             taskNum = form.cleaned_data("listNum")

#             taskList[taskNum] = task
#             request.session["tasks"] = [taskList]
#             print(request.session["tasks"])

#             return HttpResponseRedirect(reverse("tasks:home"))
            
#     return render(request, "tasks.html", {
#         "form" : EditTaskForm(),
#         "tasks" : request.session["tasks"]
#     })

def clearSesh(request):
    request.session['tasks'] = []
    return render(request, "tasks.html", {
        "tasks" : request.session["tasks"]
    })

def editTask(request):
    if request.method == "POST":    

        taskNum = request.POST.get("taskNum")
        updateTask = request.POST.get("updateTask")

        form = EditTaskForm(request.POST)
        if form.is_valid():
            updateTask = form.cleaned_data["updateTask"]
            taskNum = form.cleaned_data["taskNum"]
            request.session["tasks"][int(taskNum) - 1] = updateTask
            print(updateTask)
            print(taskNum)
            print(request.session["tasks"][int(taskNum) - 1])

            return HttpResponseRedirect(reverse("tasks:home"))
        else:
            print("form not valid")

    return render(request, "tasks.html", {
        "formEdit" : EditTaskForm()
    })

Django-Python/sampleproject/index/templates/index/index.html
{% extends "index/template.html" %}

{% block body %}
        <p>Your name is {{ name }}</p>
        <p>Pleased to meet you!</p>
{% endblock %}
<a href="{% url 'index/timeDisplay' %}">time check(?)</a>

Django-Python/sampleproject/index/templates/index/synchro.html
{% extends "index/template.html" %}

{% block body %}
    <ul>
        {% for man in men %}
            <li>{{ man }}</li>
        {% endfor %}
    </ul>
{% endblock %}

Django-Python/sampleproject/index/templates/index/template.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Start Page</title>
    </head>
    <body>
        <h2>I think this is a header</h2>
        {% block body %}
        {% endblock %}
        <a href="{% url 'index' %}">Click here to leave(?)</a>
        <h2>A Michael Joshua P. Sarmiento Production</h2>
    </body>
</html>

Django-Python/sampleproject/newyear/templates/newyear/newyear.html
{% extends "newyear/template.html" %}

{% block body %}
    {% if currDate %}
    <h3>YES</h3>
    {% else %}
    <h3>NO</h3>
    {% endif %}
{% endblock %}

Django-Python/sampleproject/newyear/templates/newyear/template.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Start Page</title>
    </head>
    <body>
        <h2>New Year's Day</h2>
        {% block body %}
        {% endblock %}
        <h2>New Year's Eve?</h2>
    </body>
</html>

Django-Python/sampleproject/tasks/templates/add.html
{% extends "template.html" %}

{% block body %}

<h3>Add Here!</h3>

<form action="" method="post">
    {% csrf_token %}
    <!-- <input type="text" name="task"> -->
    {{ form }}
    <input type="submit">
</form>
<br>
<a href="{% url 'tasks:home' %}">Home</a>

{% endblock %}

Django-Python/sampleproject/tasks/templates/tasks.html
{% extends "template.html" %}

{% block body %}

<h3>View Here!</h3>

<ol>
    {% for task in tasks %}
    <li>{{ task }}</li>
    {% empty %}
    <h3>No Tasks</h3>
    {% endfor %}
</ol>

<a href="{% url 'tasks:add' %}">Add your new task here!</a>

<br>

<h3>Edit:</h3>
<form action="" method="post">
    {% csrf_token %}
    {{ formEdit }}
    <input type="submit">
</form>

<h3>Delete:</h3>
<form action="" method="post">
    {% csrf_token %}
    <h4>Count</h4>
    <input type="text" name="listNum">
    <br><br>
    <input type="submit">
</form>

<br>

<a href="{% url 'tasks:clear' %}">Clear Session</a>

{% endblock %}

Django-Python/sampleproject/tasks/templates/template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasks</title>
</head>
<body>

    <h1>Tasks Page</h1>

    {% block body %}

    {% endblock %}

</body>
</html>